baseURL = "https://warlock3414.netlify.app/"
languageCode = "en-us"
title = "warlock3414"
theme = "terminal"
[pagination]
  pagerSize = 5

[params]
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true

[[menu.main]]
  identifier = "about"
  name = "about"
  url = "/about"

[[menu.main]]
  identifier = "posts"
  name = "posts"
  url = "/posts"

[params.homeSubtitle]
  enabled = true

[params.social]
  github = "Ram-Narayan-3414"
  linkedin = "ramanarayan-av"

[params.Logo]
  logoText = "Warlock3414"
  logoHomeLink = "/"
